#!/usr/bin/env python

import os
import sys

FILENAME = 'gabrielziegler_master_thesis'


def transfer_files_from_compilation_folder(filename):
    extensions = ('aux', 'bbl', 'blg', 'lof', 'log', 'lot', 'toc')
    for ext in extensions:
        f = f'{filename}.{ext}'
        if os.path.exists(f'compilation_files/{f}'):
            os.system(f'mv compilation_files/{f} ./')

    for f in ('totalpoints.tex', 'totalnumberquestions.tex'):
        if os.path.exists(f'compilation_files/{f}'):
            os.system(f'mv compilation_files/{f} ./')


def transfer_files_to_compilation_folder(filename):
    extensions = ('aux', 'bbl', 'blg', 'lof', 'log', 'lot')
    for ext in extensions:
        f = f'{filename}.{ext}'
        if os.path.exists(f):
            os.system(f'mv {f} compilation_files/')

    for f in ('totalpoints.tex', 'totalnumberquestions.tex'):
        if os.path.exists(f):
            os.system(f'mv {f} compilation_files/')


def main():
    transfer_files_from_compilation_folder(FILENAME)
    if len(sys.argv) == 1 or sys.argv[1] == 'simple':
        os.system(f'pdflatex -shell-escape {FILENAME}')
    elif len(sys.argv) == 2 and sys.argv[1] == 'bibtex':
        os.system(f'bibtex {FILENAME}')
    elif len(sys.argv) == 2 and sys.argv[1] == 'full':
        os.system(f'pdflatex -shell-escape {FILENAME}')
        os.system(f'bibtex {FILENAME}')
        os.system(f'pdflatex -shell-escape {FILENAME}')
        os.system(f'pdflatex -shell-escape {FILENAME}')
    transfer_files_to_compilation_folder(FILENAME)


if __name__ == '__main__':
    main()

